### ISSUE TITLE
missing <fa> component

### ISSUE THREAD

**Issue by YacoubBelaoura** [enso-ui/dropdown-indicator#1]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

<fa> - missing the font-awesome. vue component

### Steps to Reproduce
installing @enso-ui/select or @enso-ui/dropdown-indicator on a non enso project
it will throw a console error for missing <fa> component
![missing-fa](https://user-images.githubusercontent.com/18699402/54914213-bd835b80-4ef4-11e9-95f4-74a0cb1d9d5f.png)

### My workaround
i added
```javascript
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
...
    components:{
         'fa':FontAwesomeIcon
    },
```

**Comment by aocneanu** [comment]
Yes, you are correct. A mention should be added to the whole FE docs.

@gandesc , when you have the time.

**Comment by aocneanu** [comment]
And the same for axios.

**Comment by gandesc** [comment]
Docs were updated
